name: Java CI with Gradle

on: 
  push:
    branches:
      - main  # або master, залежно від вашої гілки

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Крок 1: Перевірка коду з GitHub
    - name: Checkout code
      uses: actions/checkout@v2

    # Крок 2: Встановлення JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    # Крок 3: Збірка Gradle проєкту
    - name: Build with Gradle
      run: ./gradlew build
